# Generated by Django 4.2.9 on 2024-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='valami',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
