# Generated by Django 4.2.9 on 2024-02-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_content_message_content2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
