# Generated by Django 4.2.9 on 2024-02-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sender',
            new_name='last_friend',
        ),
    ]
