# Generated by Django 4.2.10 on 2024-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_sender_customer_last_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
