# Generated by Django 4.2.10 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_delivery_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
