# Generated by Django 4.2.10 on 2024-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sold_products', models.IntegerField(default=0)),
                ('total_posts_created', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cég Információk',
            },
        ),
    ]
