# Generated by Django 4.2.10 on 2024-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='post_model_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='user_model_updated',
            field=models.BooleanField(default=False),
        ),
    ]
