# Generated by Django 4.2.10 on 2024-03-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_companyinfo_post_model_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='post_model_updated',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='total_customers',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='total_posts_created',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='total_sold_products',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='user_model_updated',
        ),
    ]
