# Generated by Django 4.2.10 on 2024-03-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
