# Generated by Django 4.2.10 on 2024-03-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_profile_comment_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
    ]
